import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import "flowbite";
import Navber from "@/Components/Navber";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${outfit.variable} antialiased bg-gradient-to-b from-[#d2dbdd] to-[#eff0db] min-h-screen w-full`}>
        <Navber />
        {children}
      </body>
    </html>
  );
}
